Fix: Android build conflict
Exclude Android (ARMv7) from Plugins/QuickJS/x64/libquickjs.so to prevent a conflict with the existing Android ARMv7 plugin at Plugins/QuickJS/Android/libs/armeabi-v7a/libquickjs.so.

This resolves the following Unity build error:

Exception: Cannot include plugin '.../armeabi-v7a/libquickjs.so' (Key: libquickjs.so;ARMv7) since plugin with the same name and architecture was already added ('.../x64/libquickjs.so (Architecture: ARMv7)').